- name: Add NVIDIA package repositories
  hosts: "*"
  tasks:
    - name: "wget packet contents for cuda"
      shell: 'wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-ubuntu1804.pin'

    - name: "move downloaded *.pin"
      command: 'mv cuda-ubuntu1804.pin /etc/apt/preferences.d/cuda-repository-pin-600'
      become: true

    - name: "add nvidia-key"
      shell: 'apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub'
      become: true

    - name: "add apt nvidia repository"
      shell: 'add-apt-repository "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/ /"'
      become: true

    - name: "apt update"
      apt:
        upgrade: no
        update_cache: true
      become: true

    - name: "wget packet contents for nvidia ML"
      shell: 'wget http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64/nvidia-machine-learning-repo-ubuntu1804_1.0.0-1_amd64.deb'

    - name: "install fetched package"
      shell: 'apt install ./nvidia-machine-learning-repo-ubuntu1804_1.0.0-1_amd64.deb'
      become: true

    - name: "apt update"
      apt:
        upgrade: no
        update_cache: true
      become: true

    - name: "wget packet contents for nvidia ML"
      shell: 'wget https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64/libnvinfer7_7.1.3-1+cuda11.0_amd64.deb'

    - name: "install fetched package"
      shell: 'apt install ./libnvinfer7_7.1.3-1+cuda11.0_amd64.deb'
      become: true

    - name: "apt update"
      apt:
        upgrade: no
        update_cache: true
      become: true

    - name: "install development and runtime libraries (~4GB)"
      shell: 'apt-get install --no-install-recommends \
              cuda-11-0 \
              libcudnn8=8.0.4.30-1+cuda11.0  \
              libcudnn8-dev=8.0.4.30-1+cuda11.0'
      become: true

    - name: "Print message to user"
      ansible.builtin.debug:
        msg: "* PLEASE REBOOT YOUR SYSTEM AND RUN NEXT SCRIPT *"
